sudo: false

language: go
go:
  - 1.5.1

addons:
  apt:
    packages:
      - python-virtualenv

before_install:
  # This is needed so the package path uses elastic/winlogbeat as its path.
  - mkdir -p $HOME/gopath/src/github.com/elastic/winlogbeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/elastic/winlogbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/elastic/winlogbeat
  - cd $HOME/gopath/src/github.com/elastic/winlogbeat

install:
  - make deps

script:
  - make check
  - make winlogbeat
  - make testsuite
  - make crosscompile
